# Pre-commit configuration for QU Security Backend
# Run: pre-commit install to set up the git hook scripts

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [django-stubs, djangorestframework-stubs, types-pytz]
        args: [
          --ignore-missing-imports,
          --no-strict-optional,
          --allow-untyped-defs,
          --disable-error-code=var-annotated,
          --disable-error-code=union-attr,
          --disable-error-code=list-item
        ]
        exclude: ^(migrations/|core/management/commands/)

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        additional_dependencies: ["pbr"]
        args: [
          --configfile, "pyproject.toml",
          --format, "custom",
          --msg-template, "{abspath}:{line}: {test_id}[bandit]: {severity}: {msg}"
        ]
