# Generated by Django 5.2.5 on 2025-09-08 14:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_property_contract_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Budget ($)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rate per Hour ($)'),
        ),
    ]
