# Generated by Django 5.2.5 on 2025-09-08 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_service_monthly_budget_alter_service_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='recurrent',
            field=models.BooleanField(default=False, help_text='Whether this service is performed on a recurring basis', verbose_name='Recurrent'),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, help_text='Dates when this service is scheduled to be performed', null=True, size=None, verbose_name='Schedule Dates'),
        ),
    ]
