# Generated by Django 5.2.5 on 2025-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_schedule_recurrent_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Time when this service ends each day', null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Time when this service starts each day', null=True, verbose_name='Start Time'),
        ),
    ]
