# Generated by Django 5.2.5 on 2025-09-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_start_end_time_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='planned_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned End Time'),
        ),
        migrations.AddField(
            model_name='shift',
            name='planned_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned Start Time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
