# Generated by Django 5.2.5 on 2025-09-10 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_planned_time_to_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='core.weapon', verbose_name='Weapon'),
        ),
    ]
