# Generated by Django 5.2.5 on 2025-09-17 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_shift_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date when this service ends (MM/DD/YYYY format)', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='service',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when this service begins (MM/DD/YYYY format)', null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='service',
            name='weekly',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, help_text='Days of the week when this service is performed (e.g., Monday, Tuesday)', null=True, size=None, verbose_name='Weekly Schedule'),
        ),
    ]
