# Generated by Django 5.2.5 on 2025-09-19 02:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_service_end_date_service_start_date_service_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='scheduled_total_hours',
            field=models.PositiveIntegerField(default=0, help_text='Total scheduled hours for this service', verbose_name='Scheduled Total Hours'),
        ),
        migrations.AlterField(
            model_name='service',
            name='weekly',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10), blank=True, default=list, help_text='Days of the week when this service is performed', null=True, size=None, verbose_name='Weekly Schedule'),
        ),
    ]
