# Generated by Django 5.2.5 on 2025-09-19 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_service_scheduled_total_hours_alter_service_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='planned_hours_worked',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated hours between planned start and end times', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Planned Hours Worked'),
        ),
    ]
