# Generated by Django 5.2.5 on 2025-09-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_shift_planned_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_hours',
            field=models.PositiveIntegerField(default=0, help_text='Total hours worked for this service', verbose_name='Total Hours'),
        ),
        migrations.AddField(
            model_name='service',
            name='total_hours_planned',
            field=models.PositiveIntegerField(default=0, help_text='Total planned hours for this service', verbose_name='Total Planned Hours'),
        ),
    ]
