# Generated by Django 5.2.5 on 2025-09-25 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_by'], name='core_note_created_e03cfe_idx'),
        ),
    ]
