# Generated by Django 5.2.5 on 2025-09-26 14:03

import django.contrib.postgres.fields
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_created_by_to_note'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='note',
            name='core_note_amount_4016bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='core_note_client__bb8309_idx',
        ),
        migrations.RemoveField(
            model_name='note',
            name='client',
        ),
        migrations.RemoveField(
            model_name='note',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='note',
            name='guard',
        ),
        migrations.RemoveField(
            model_name='note',
            name='guard_property_tariff',
        ),
        migrations.RemoveField(
            model_name='note',
            name='property_obj',
        ),
        migrations.RemoveField(
            model_name='note',
            name='property_type_of_service',
        ),
        migrations.RemoveField(
            model_name='note',
            name='service',
        ),
        migrations.RemoveField(
            model_name='note',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='note',
            name='weapon',
        ),
        migrations.AddField(
            model_name='note',
            name='clients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, help_text='Array of client IDs associated with this note', size=None, verbose_name='Clients'),
        ),
        migrations.AddField(
            model_name='note',
            name='guards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, help_text='Array of guard IDs associated with this note', size=None, verbose_name='Guards'),
        ),
        migrations.AddField(
            model_name='note',
            name='properties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, help_text='Array of property IDs associated with this note', size=None, verbose_name='Properties'),
        ),
        migrations.AddField(
            model_name='note',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, help_text='Array of service IDs associated with this note', size=None, verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='note',
            name='shifts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, help_text='Array of shift IDs associated with this note', size=None, verbose_name='Shifts'),
        ),
        migrations.AddField(
            model_name='note',
            name='type_of_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, help_text='Array of property type of service IDs associated with this note', size=None, verbose_name='Type of Services'),
        ),
        migrations.AddField(
            model_name='note',
            name='viewed_by_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, help_text='Array of user IDs who have viewed this note', size=None, verbose_name='Viewed by'),
        ),
        migrations.AddField(
            model_name='note',
            name='weapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, help_text='Array of weapon IDs associated with this note', size=None, verbose_name='Weapons'),
        ),
        migrations.AlterField(
            model_name='note',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Financial amount - can be positive (income) or negative (expense)', max_digits=12, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=12)], verbose_name='Amount ($)'),
        ),
    ]
