# Generated by Django 5.2.5 on 2025-09-06 23:15

import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A human-readable name for the API key.', max_length=100, unique=True, verbose_name='name')),
                ('key', models.CharField(db_index=True, help_text='The unique API key.', max_length=64, unique=True, verbose_name='key')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to disable the API key without deleting it.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ('-created_at',),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
