# Generated by Django 5.2.5 on 2025-09-07 21:24

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_property_contract_start_date_and_more'),
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(help_text='Attached file for this report.', upload_to='guard_reports/%Y/%m/%d/', verbose_name='file')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('report_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='report datetime')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude in decimal degrees (-90 to 90).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees (-180 to 180).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.guard', verbose_name='Guard')),
            ],
            options={
                'verbose_name': 'Guard Report',
                'verbose_name_plural': 'Guard Reports',
                'ordering': ('-report_datetime', '-created_at'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
