# Generated by Django 5.2.5 on 2025-09-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_alter_guardreport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardreport',
            name='file',
            field=models.FileField(help_text='Attached file for this report.', upload_to='guard_reports/%Y/%m/%d/', verbose_name='file'),
        ),
    ]
