# Generated by Django 5.2.5 on 2025-09-25 17:10

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_alter_guardreport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardreport',
            name='file',
            field=models.FileField(help_text='Attached file for this report.', storage=core.storages.MediaStorage(), upload_to='guard_reports/%Y/%m/%d/', verbose_name='file'),
        ),
    ]
