name: Docker Compose CD

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    name: Run Docker Compose
    runs-on: rolloco

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and run containers
        run: |
          docker compose --file deploy/docker-compose.yml up -d --build